# 1. 텐서플로우(TenserFlow)

* 텐서플로우는 ML모델을 개발하고 학습시키는데 도움이 되는 핵심 오픈 소스 라이브러리
* 텐서플로우 2.x에서는 케라스를 딥러닝 공식 API로 채택하였고, 텐서플로우 내의 하나의 프레임워크로 개발되고 있음

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.8.2


### 1-1. Tensor
* Tensor는 multi-dimensional array를 나타내는 말
* Tensor flow의 기본 data type

In [ ]:
hello = tf.constant([3, 3], dtype=tf.float32) # [3, 3] 정보가 들어간 실수 타입의 상수 객체
print(hello)

hello = tf.constant('Hello Tensor!!')
print(hello)

tf.Tensor([3. 3.], shape=(2,), dtype=float32)
tf.Tensor(b'Hello Tensor!!', shape=(), dtype=string)


In [ ]:
x = tf.constant([[1.0, 2.0], [3.0, 4.0]])
print(x)
print(type(x))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
import numpy as np

In [ ]:
x_np = np.array([[1.0, 2.0], 
                 [3.0, 4.0]])
x_list = [[1.0, 2.0], 
          [3.0, 4.0]]

print(type(x_np))
print(type(x_list))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
# ndarray -> tensor
x_np_tf = tf.convert_to_tensor(x_np)
print(type(x_np_tf))

# list -> tensor
x_list_tf = tf.convert_to_tensor(x_np)
print(type(x_list_tf))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
# tensor -> ndarray
print(x_np_tf.numpy())
print(type(x_np_tf.numpy()))

[[1. 2.]
 [3. 4.]]
<class 'numpy.ndarray'>


### 1-2. 텐서플로우 함수

In [ ]:
a = tf.ones((2,3))
print(a)

b = tf.zeros((2,3))
print(b)

c = tf.fill((2,3), 2)
print(c)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2 2 2]
 [2 2 2]], shape=(2, 3), dtype=int32)


In [ ]:
d = tf.zeros_like(c) # shape와 dtype만 복사(데이터는 복사하지 않음)
print(d)

e = tf.ones_like(c)
print(e)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [ ]:
g = tf.range(10)
print(g)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [ ]:
h = tf.random.uniform((2,2)) # 0 < h < 1 의 랜덤한 값을 2행 2열로 추출
print(h)

i = tf.random.normal((2,2)) # -2 < i < 2 의 랜덤한 값을 2핻 2열로 추출
print(i)

tf.Tensor(
[[0.84443355 0.7043824 ]
 [0.22586548 0.7143545 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.43258655 -0.88945156]
 [ 1.0182232   0.6035931 ]], shape=(2, 2), dtype=float32)


### 1-3. Tensor의 속성

In [ ]:
tensor = tf.random.normal((3,4))
print(f'Shape: {tensor.shape}')
print(f'DataType: {tensor.dtype}')

Shape: (3, 4)
DataType: <dtype: 'float32'>


In [ ]:
tensor = tf.reshape(tensor, (4,3)) # Shape 변경
tensor = tf.cast(tensor, tf.int32) # dtype 변경
print(f'Shape: {tensor.shape}')
print(f'DataType: {tensor.dtype}')

Shape: (4, 3)
DataType: <dtype: 'int32'>


### 1-4. Variable
* Variable은 변할 수 있는 상태를 저장하는데 사용되는 특별한 텐서
* 딥러닝에서는 학습해야 하는 가중치(Weight, bias)등을 Variable로 생성

In [ ]:
tensor = tf.ones((3,4)) # constant로 생성되어서 수정할 수가 없음
print(tensor)

tensor[0,0] = 100 # TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


TypeError: ignored

In [ ]:
# 데이터를 변경하고 싶으면 Variable 형태로 바꿔준 후 assign 함수를 사용해야 함

# assign() : 값 설정
# assign_add() : 값 더하기
# assign_sub() : 값 빼기;

var = tf.Variable(tensor)
print(var)

var[0,0].assign(100)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>


<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=float32, numpy=
array([[100.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]], dtype=float32)>

In [ ]:
value1 = tf.random.normal(shape=(2,2))
value1 = tf.Variable(value1) # 변수로 변경해서 다시 저장
print(value1)
value2 = tf.random.normal(shape=(2,2))
print(value2)
value1.assign(value2)
print(value1)

value3 = tf.ones(shape=(2,2))
value1.assign_add(value1)
print(value1)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-1.028244 ,  1.0233562],
       [ 1.0178035, -1.5274178]], dtype=float32)>
tf.Tensor(
[[ 1.1093764  -1.9463631 ]
 [ 0.6311572  -0.45157963]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.1093764 , -1.9463631 ],
       [ 0.6311572 , -0.45157963]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 2.2187529 , -3.8927262 ],
       [ 1.2623144 , -0.90315926]], dtype=float32)>


### 1-5. indexing과 slicing

In [ ]:
a = tf.range(1, 13)
print(a)

a = tf.reshape(a, (3, 4))
print(a)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)


In [ ]:
# 인덱싱을 하면 차원이 감소하게 됨
print(a[1])
print(a[0, -1])

tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
# 슬라이싱은 차원이 유지됨
print(a[1:-1])
print(a[:2, 2:])

tf.Tensor([[5 6 7 8]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[3 4]
 [7 8]], shape=(2, 2), dtype=int32)


### 1-6. 차원 바꾸기

In [ ]:
a = tf.range(16)
print(a)

a = tf.reshape(a, (2,2,-1)) # 2,2,-1: 면,행,열. -1은 자동으로 만들라는 의미
print(a)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15], shape=(16,), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]], shape=(2, 2, 4), dtype=int32)


In [ ]:
# transpose: 행렬의 차원을 인덱스로 변환
# a는 2,2,4 -> transpose -> 4,2,2
b = tf.transpose(a, (2, 0, 1))
print(b)

tf.Tensor(
[[[ 0  4]
  [ 8 12]]

 [[ 1  5]
  [ 9 13]]

 [[ 2  6]
  [10 14]]

 [[ 3  7]
  [11 15]]], shape=(4, 2, 2), dtype=int32)


### 1-7. Tensor 연산

In [ ]:
x = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
y = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)
print(x)
print(y)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


In [ ]:
print(tf.add(x, y))
print(tf.subtract(x, y))
print(tf.multiply(x, y))
print(tf.divide(x, y))
print(tf.matmul(x, y)) # 행렬곱

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [ ]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x @ y)

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [ ]:
z = tf.range(1, 11)
print(z)

z = tf.reshape(z, (2, 5))
print(z)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)


In [ ]:
# reduce_sum() : .요소의 합계를 구함
print(tf.reduce_sum(z))

tf.Tensor(55, shape=(), dtype=int32)


In [ ]:
sum1 = tf.reduce_sum(z, axis=0) # 행
print(sum1)

sum2 = tf.reduce_sum(z, axis=1)
print(sum2)

sum3 = tf.reduce_sum(z, axis=-1) # 열. 마지막 방향
print(sum3)

tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int32)
tf.Tensor([15 40], shape=(2,), dtype=int32)


In [ ]:
# concat() : 행과 열을 합침
concat = tf.concat([z, z], axis=0)
print(concat)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(4, 5), dtype=int32)


In [ ]:
concat = tf.concat([z, z], axis=1)
print(concat)

tf.Tensor(
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]], shape=(2, 10), dtype=int32)


In [ ]:
concat = tf.concat([z, z], axis=-1)
print(concat)

tf.Tensor(
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]], shape=(2, 10), dtype=int32)
